{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "관련 라이브러리 설치"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Looking in indexes: https://pypi.anaconda.org/intel/simple, https://pypi.org/simple\n",
      "Collecting numpy==1.20.3\n",
      "  Downloading https://pypi.anaconda.org/intel/simple/numpy/1.20.3/numpy-1.20.3-1-cp38-cp38-manylinux2014_x86_64.whl (7.8 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m7.8/7.8 MB\u001b[0m \u001b[31m3.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m0m\n",
      "\u001b[?25hCollecting mkl\n",
      "  Using cached mkl-2022.2.1-py2.py3-none-manylinux1_x86_64.whl (259.9 MB)\n",
      "Collecting tbb4py\n",
      "  Using cached tbb4py-2021.6.3-py38-none-manylinux1_x86_64.whl (445 kB)\n",
      "Collecting mkl_fft\n",
      "  Using cached mkl_fft-1.3.1-17-cp38-cp38-manylinux2014_x86_64.whl (252 kB)\n",
      "Collecting mkl_random\n",
      "  Using cached mkl_random-1.2.2-17-cp38-cp38-manylinux2014_x86_64.whl (420 kB)\n",
      "Collecting mkl-service\n",
      "  Using cached mkl_service-2.4.0-11-cp38-cp38-manylinux2014_x86_64.whl (65 kB)\n",
      "Collecting dpcpp_cpp_rt\n",
      "  Using cached dpcpp_cpp_rt-2022.2.1-py2.py3-none-manylinux1_x86_64.whl (3.9 MB)\n",
      "Collecting mkl_umath\n",
      "  Using cached mkl_umath-0.1.1-27-cp38-cp38-manylinux2014_x86_64.whl (319 kB)\n",
      "Collecting intel-opencl-rt==2022.2.1\n",
      "  Using cached intel_opencl_rt-2022.2.1-py2.py3-none-manylinux1_x86_64.whl (253.4 MB)\n",
      "Collecting intel-cmplr-lic-rt==2022.2.1\n",
      "  Using cached intel_cmplr_lic_rt-2022.2.1-py2.py3-none-manylinux1_x86_64.whl (18 kB)\n",
      "Collecting intel-cmplr-lib-rt==2022.2.1\n",
      "  Using cached intel_cmplr_lib_rt-2022.2.1-py2.py3-none-manylinux1_x86_64.whl (33.1 MB)\n",
      "Collecting intel-openmp==2022.2.1\n",
      "  Using cached intel_openmp-2022.2.1-py2.py3-none-manylinux1_x86_64.whl (12.6 MB)\n",
      "Collecting tbb==2021.*\n",
      "  Using cached tbb-2021.7.1-py2.py3-none-manylinux1_x86_64.whl (4.0 MB)\n",
      "Collecting mkl_fft\n",
      "  Using cached mkl_fft-1.3.0-1-cp38-cp38-manylinux2014_x86_64.whl (250 kB)\n",
      "INFO: pip is looking at multiple versions of mkl-fft to determine which version is compatible with other requirements. This could take a while.\n",
      "INFO: pip is looking at multiple versions of mkl to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting mkl\n",
      "  Downloading mkl-2022.2.0-py2.py3-none-manylinux1_x86_64.whl (259.9 MB)\n",
      "\u001b[2K     \u001b[91m━━━━━━━━━━━━━━━━\u001b[0m\u001b[91m╸\u001b[0m\u001b[90m━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m114.0/259.9 MB\u001b[0m \u001b[31m57.6 MB/s\u001b[0m eta \u001b[36m0:00:03\u001b[0m\n",
      "\u001b[?25h\u001b[31mERROR: Could not install packages due to an OSError: [Errno 28] 장치에 남은 공간이 없음\n",
      "\u001b[0m\u001b[31m\n",
      "\u001b[0m--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_internal/utils/logging.py\", line 177, in emit\n",
      "    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_vendor/rich/console.py\", line 1752, in print\n",
      "    extend(render(renderable, render_options))\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_vendor/rich/console.py\", line 1390, in render\n",
      "    for render_output in iter_render:\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_internal/utils/logging.py\", line 134, in __rich_console__\n",
      "    for line in lines:\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_vendor/rich/segment.py\", line 245, in split_lines\n",
      "    for segment in segments:\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_vendor/rich/console.py\", line 1368, in render\n",
      "    renderable = rich_cast(renderable)\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_vendor/rich/protocol.py\", line 36, in rich_cast\n",
      "    renderable = cast_method()\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_internal/self_outdated_check.py\", line 130, in __rich__\n",
      "    pip_cmd = get_best_invocation_for_this_pip()\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_internal/utils/entrypoints.py\", line 58, in get_best_invocation_for_this_pip\n",
      "    if found_executable and os.path.samefile(\n",
      "  File \"/usr/lib/python3.8/genericpath.py\", line 101, in samefile\n",
      "    s2 = os.stat(f2)\n",
      "FileNotFoundError: [Errno 2] 그런 파일이나 디렉터리가 없습니다: '/usr/bin/pip3.8'\n",
      "Call stack:\n",
      "  File \"/home/ahnsunghyun/.local/bin/pip\", line 8, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_internal/cli/main.py\", line 70, in main\n",
      "    return command.main(cmd_args)\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py\", line 101, in main\n",
      "    return self._main(args)\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py\", line 223, in _main\n",
      "    self.handle_pip_version_check(options)\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py\", line 148, in handle_pip_version_check\n",
      "    pip_self_version_check(session, options)\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_internal/self_outdated_check.py\", line 237, in pip_self_version_check\n",
      "    logger.info(\"[present-rich] %s\", upgrade_prompt)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1446, in info\n",
      "    self._log(INFO, msg, args, **kwargs)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1589, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1599, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1661, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 954, in handle\n",
      "    self.emit(record)\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_internal/utils/logging.py\", line 179, in emit\n",
      "    self.handleError(record)\n",
      "Message: '[present-rich] %s'\n",
      "Arguments: (UpgradePrompt(old='22.1.2', new='22.3.1'),)\n",
      "Collecting asn1crypto==0.24.0\n",
      "  Downloading asn1crypto-0.24.0-py2.py3-none-any.whl (101 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m101.6/101.6 kB\u001b[0m \u001b[31m2.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hCollecting certifi==2019.6.16\n",
      "  Downloading certifi-2019.6.16-py2.py3-none-any.whl (157 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m157.1/157.1 kB\u001b[0m \u001b[31m39.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hCollecting cffi==1.12.3\n",
      "  Downloading cffi-1.12.3.tar.gz (456 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m456.3/456.3 kB\u001b[0m \u001b[31m50.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hRequirement already satisfied: chardet==3.0.4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (3.0.4)\n",
      "Collecting cryptography==2.7\n",
      "  Downloading cryptography-2.7-cp34-abi3-manylinux1_x86_64.whl (2.3 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.3/2.3 MB\u001b[0m \u001b[31m49.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hCollecting cycler==0.10.0\n",
      "  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)\n",
      "Requirement already satisfied: idna==2.8 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 7)) (2.8)\n",
      "Collecting joblib==0.13.2\n",
      "  Downloading joblib-0.13.2-py2.py3-none-any.whl (278 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m278.9/278.9 kB\u001b[0m \u001b[31m45.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hCollecting kiwisolver==1.1.0\n",
      "  Downloading kiwisolver-1.1.0-cp38-cp38-manylinux1_x86_64.whl (91 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m91.7/91.7 kB\u001b[0m \u001b[31m26.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hCollecting matplotlib==3.1.0\n",
      "  Downloading matplotlib-3.1.0.tar.gz (37.2 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m37.2/37.2 MB\u001b[0m \u001b[31m34.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting numpy==1.16.4\n",
      "  Downloading numpy-1.16.4.zip (5.1 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m5.1/5.1 MB\u001b[0m \u001b[31m47.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hRequirement already satisfied: olefile==0.46 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 12)) (0.46)\n",
      "Requirement already satisfied: Pillow>=7.1.0 in /home/ahnsunghyun/.local/lib/python3.8/site-packages (from -r requirements.txt (line 13)) (8.4.0)\n",
      "Collecting pycparser==2.19\n",
      "  Downloading pycparser-2.19.tar.gz (158 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m158.3/158.3 kB\u001b[0m \u001b[31m41.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting pyOpenSSL==19.0.0\n",
      "  Downloading pyOpenSSL-19.0.0-py2.py3-none-any.whl (53 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m53.3/53.3 kB\u001b[0m \u001b[31m15.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hCollecting pyparsing==2.4.0\n",
      "  Downloading pyparsing-2.4.0-py2.py3-none-any.whl (62 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m62.3/62.3 kB\u001b[0m \u001b[31m18.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hCollecting PySocks==1.7.0\n",
      "  Downloading PySocks-1.7.0-py3-none-any.whl (16 kB)\n",
      "Collecting python-dateutil==2.8.0\n",
      "  Downloading python_dateutil-2.8.0-py2.py3-none-any.whl (226 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m226.8/226.8 kB\u001b[0m \u001b[31m47.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hCollecting pytz==2019.1\n",
      "  Downloading pytz-2019.1-py2.py3-none-any.whl (510 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m510.9/510.9 kB\u001b[0m \u001b[31m47.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hCollecting pyzmq==18.0.2\n",
      "  Downloading pyzmq-18.0.2.tar.gz (1.2 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.2/1.2 MB\u001b[0m \u001b[31m48.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting requests==2.22.0\n",
      "  Downloading requests-2.22.0-py2.py3-none-any.whl (57 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m58.0/58.0 kB\u001b[0m \u001b[31m15.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hCollecting scikit-learn==0.21.2\n",
      "  Downloading scikit-learn-0.21.2.tar.gz (12.2 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m12.2/12.2 MB\u001b[0m \u001b[31m44.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting scipy==1.3.0\n",
      "  Downloading scipy-1.3.0.tar.gz (23.6 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m23.6/23.6 MB\u001b[0m \u001b[31m35.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n",
      "\u001b[?25h  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25ldone\n",
      "\u001b[?25h  Preparing metadata (pyproject.toml) ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mPreparing metadata \u001b[0m\u001b[1;32m(\u001b[0m\u001b[32mpyproject.toml\u001b[0m\u001b[1;32m)\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[150 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m <string>:111: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n",
      "  \u001b[31m   \u001b[0m <string>:386: UserWarning: Unrecognized setuptools command ('dist_info --output-dir /tmp/pip-modern-metadata-lha517f0 --keep-egg-info'), proceeding with generating Cython sources and expanding templates\n",
      "  \u001b[31m   \u001b[0m Running from scipy source directory.\n",
      "  \u001b[31m   \u001b[0m lapack_opt_info:\n",
      "  \u001b[31m   \u001b[0m lapack_mkl_info:\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']\n",
      "  \u001b[31m   \u001b[0m   NOT AVAILABLE\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m openblas_lapack_info:\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries openblas not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']\n",
      "  \u001b[31m   \u001b[0m   NOT AVAILABLE\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m openblas_clapack_info:\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']\n",
      "  \u001b[31m   \u001b[0m   NOT AVAILABLE\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m atlas_3_10_threads_info:\n",
      "  \u001b[31m   \u001b[0m Setting PTATLAS=ATLAS\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries tatlas,tatlas not found in /usr/local/lib\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries lapack_atlas not found in /usr/local/lib\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries tatlas,tatlas not found in /usr/lib64\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries lapack_atlas not found in /usr/lib64\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries tatlas,tatlas not found in /usr/lib\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries lapack_atlas not found in /usr/lib\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu\n",
      "  \u001b[31m   \u001b[0m <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>\n",
      "  \u001b[31m   \u001b[0m   NOT AVAILABLE\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m atlas_3_10_info:\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries satlas,satlas not found in /usr/local/lib\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries lapack_atlas not found in /usr/local/lib\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries satlas,satlas not found in /usr/lib64\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries lapack_atlas not found in /usr/lib64\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries satlas,satlas not found in /usr/lib\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries lapack_atlas not found in /usr/lib\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu\n",
      "  \u001b[31m   \u001b[0m <class 'numpy.distutils.system_info.atlas_3_10_info'>\n",
      "  \u001b[31m   \u001b[0m   NOT AVAILABLE\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m atlas_threads_info:\n",
      "  \u001b[31m   \u001b[0m Setting PTATLAS=ATLAS\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries lapack_atlas not found in /usr/local/lib\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries ptf77blas,ptcblas,atlas not found in /usr/lib64\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries lapack_atlas not found in /usr/lib64\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries ptf77blas,ptcblas,atlas not found in /usr/lib\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries lapack_atlas not found in /usr/lib\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu\n",
      "  \u001b[31m   \u001b[0m <class 'numpy.distutils.system_info.atlas_threads_info'>\n",
      "  \u001b[31m   \u001b[0m   NOT AVAILABLE\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m atlas_info:\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries f77blas,cblas,atlas not found in /usr/local/lib\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries lapack_atlas not found in /usr/local/lib\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries f77blas,cblas,atlas not found in /usr/lib64\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries lapack_atlas not found in /usr/lib64\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries f77blas,cblas,atlas not found in /usr/lib\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries lapack_atlas not found in /usr/lib\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu\n",
      "  \u001b[31m   \u001b[0m <class 'numpy.distutils.system_info.atlas_info'>\n",
      "  \u001b[31m   \u001b[0m   NOT AVAILABLE\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m /tmp/pip-build-env-cm4qcnem/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:624: UserWarning:\n",
      "  \u001b[31m   \u001b[0m     Atlas (http://math-atlas.sourceforge.net/) libraries not found.\n",
      "  \u001b[31m   \u001b[0m     Directories to search for the libraries can be specified in the\n",
      "  \u001b[31m   \u001b[0m     numpy/distutils/site.cfg file (section [atlas]) or by setting\n",
      "  \u001b[31m   \u001b[0m     the ATLAS environment variable.\n",
      "  \u001b[31m   \u001b[0m   self.calc_info()\n",
      "  \u001b[31m   \u001b[0m lapack_info:\n",
      "  \u001b[31m   \u001b[0m customize UnixCCompiler\n",
      "  \u001b[31m   \u001b[0m   libraries lapack not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']\n",
      "  \u001b[31m   \u001b[0m   NOT AVAILABLE\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m /tmp/pip-build-env-cm4qcnem/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:624: UserWarning:\n",
      "  \u001b[31m   \u001b[0m     Lapack (http://www.netlib.org/lapack/) libraries not found.\n",
      "  \u001b[31m   \u001b[0m     Directories to search for the libraries can be specified in the\n",
      "  \u001b[31m   \u001b[0m     numpy/distutils/site.cfg file (section [lapack]) or by setting\n",
      "  \u001b[31m   \u001b[0m     the LAPACK environment variable.\n",
      "  \u001b[31m   \u001b[0m   self.calc_info()\n",
      "  \u001b[31m   \u001b[0m lapack_src_info:\n",
      "  \u001b[31m   \u001b[0m   NOT AVAILABLE\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m /tmp/pip-build-env-cm4qcnem/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:624: UserWarning:\n",
      "  \u001b[31m   \u001b[0m     Lapack (http://www.netlib.org/lapack/) sources not found.\n",
      "  \u001b[31m   \u001b[0m     Directories to search for the sources can be specified in the\n",
      "  \u001b[31m   \u001b[0m     numpy/distutils/site.cfg file (section [lapack_src]) or by setting\n",
      "  \u001b[31m   \u001b[0m     the LAPACK_SRC environment variable.\n",
      "  \u001b[31m   \u001b[0m   self.calc_info()\n",
      "  \u001b[31m   \u001b[0m   NOT AVAILABLE\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 363, in <module>\n",
      "  \u001b[31m   \u001b[0m     main()\n",
      "  \u001b[31m   \u001b[0m   File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 345, in main\n",
      "  \u001b[31m   \u001b[0m     json_out['return_val'] = hook(**hook_input['kwargs'])\n",
      "  \u001b[31m   \u001b[0m   File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 164, in prepare_metadata_for_build_wheel\n",
      "  \u001b[31m   \u001b[0m     return hook(metadata_directory, config_settings)\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-build-env-cm4qcnem/overlay/lib/python3.8/site-packages/setuptools/build_meta.py\", line 377, in prepare_metadata_for_build_wheel\n",
      "  \u001b[31m   \u001b[0m     self.run_setup()\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-build-env-cm4qcnem/overlay/lib/python3.8/site-packages/setuptools/build_meta.py\", line 483, in run_setup\n",
      "  \u001b[31m   \u001b[0m     super(_BuildMetaLegacyBackend,\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-build-env-cm4qcnem/overlay/lib/python3.8/site-packages/setuptools/build_meta.py\", line 335, in run_setup\n",
      "  \u001b[31m   \u001b[0m     exec(code, locals())\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 505, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 501, in setup_package\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-build-env-cm4qcnem/overlay/lib/python3.8/site-packages/numpy/distutils/core.py\", line 135, in setup\n",
      "  \u001b[31m   \u001b[0m     config = configuration()\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 403, in configuration\n",
      "  \u001b[31m   \u001b[0m numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[?25h\u001b[1;31merror\u001b[0m: \u001b[1mmetadata-generation-failed\u001b[0m\n",
      "\n",
      "\u001b[31m×\u001b[0m Encountered error while generating package metadata.\n",
      "\u001b[31m╰─>\u001b[0m See above for output.\n",
      "\n",
      "\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\n",
      "\u001b[1;36mhint\u001b[0m: See above for details.\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_internal/utils/logging.py\", line 177, in emit\n",
      "    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_vendor/rich/console.py\", line 1752, in print\n",
      "    extend(render(renderable, render_options))\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_vendor/rich/console.py\", line 1390, in render\n",
      "    for render_output in iter_render:\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_internal/utils/logging.py\", line 134, in __rich_console__\n",
      "    for line in lines:\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_vendor/rich/segment.py\", line 245, in split_lines\n",
      "    for segment in segments:\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_vendor/rich/console.py\", line 1368, in render\n",
      "    renderable = rich_cast(renderable)\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_vendor/rich/protocol.py\", line 36, in rich_cast\n",
      "    renderable = cast_method()\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_internal/self_outdated_check.py\", line 130, in __rich__\n",
      "    pip_cmd = get_best_invocation_for_this_pip()\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_internal/utils/entrypoints.py\", line 58, in get_best_invocation_for_this_pip\n",
      "    if found_executable and os.path.samefile(\n",
      "  File \"/usr/lib/python3.8/genericpath.py\", line 101, in samefile\n",
      "    s2 = os.stat(f2)\n",
      "FileNotFoundError: [Errno 2] 그런 파일이나 디렉터리가 없습니다: '/usr/bin/pip3.8'\n",
      "Call stack:\n",
      "  File \"/home/ahnsunghyun/.local/bin/pip\", line 8, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_internal/cli/main.py\", line 70, in main\n",
      "    return command.main(cmd_args)\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py\", line 101, in main\n",
      "    return self._main(args)\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py\", line 223, in _main\n",
      "    self.handle_pip_version_check(options)\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py\", line 148, in handle_pip_version_check\n",
      "    pip_self_version_check(session, options)\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_internal/self_outdated_check.py\", line 237, in pip_self_version_check\n",
      "    logger.info(\"[present-rich] %s\", upgrade_prompt)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1446, in info\n",
      "    self._log(INFO, msg, args, **kwargs)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1589, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1599, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1661, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 954, in handle\n",
      "    self.emit(record)\n",
      "  File \"/home/ahnsunghyun/.local/lib/python3.8/site-packages/pip/_internal/utils/logging.py\", line 179, in emit\n",
      "    self.handleError(record)\n",
      "Message: '[present-rich] %s'\n",
      "Arguments: (UpgradePrompt(old='22.1.2', new='22.3.1'),)\n"
     ]
    }
   ],
   "source": [
    "!pip install -i https://pypi.anaconda.org/intel/simple --extra-index-url https://pypi.org/simple numpy==1.20.3\n",
    "!pip install --user --requirement requirements.txt"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "= 실험 주의 사항 =\n",
    "\n",
    "visdom 켜고 실험하기!!\n",
    "python3 -m visdom.server\n",
    "\n",
    "[train 예시]\n",
    "\n",
    "!python3 train.py \\\n",
    "    --dataset cifar10 \\\n",
    "    --niter 1 \\\n",
    "    --abnormal_class dog  \\\n",
    "    --nc 3 \\\n",
    "    --batchsize 64 \\\n",
    "    --display\n",
    "\n",
    "// --resume'checkpoint path' 하면 이어서 학습 가능\n",
    "\n",
    "[test 예시]\n",
    "\n",
    "!python3 test.py \\\n",
    "    --dataset cifar10 \\\n",
    "    --load_weights \\\n",
    "    --abnormal_class dog \\\n",
    "    --nc 3 \\\n",
    "    --batchsize 64 \\\n",
    "    --display"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "[MNIST] 무조건 1은 정상(학습,테스트용), 0은 비정상(테스트용) -- 성능 좋음"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/home/ahnsunghyun/.local/lib/python3.8/site-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:180.)\n",
      "  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)\n",
      "Setting up a new session...\n",
      ">> Training model Ganomaly.\n",
      ">> Training model Ganomaly. Epoch 1/10                                          \n",
      "result: OrderedDict([('Avg Run Time (ms/batch)', 6.678707599639893), ('roc', 0.8828064922293251)])\n",
      "   Avg Run Time (ms/batch): 6.679 roc: 0.883 max roc: 0.883\n",
      ">> Training model Ganomaly. Epoch 2/10                                          \n",
      "result: OrderedDict([('Avg Run Time (ms/batch)', 6.480891704559326), ('roc', 0.9504575996773413)])\n",
      "   Avg Run Time (ms/batch): 6.481 roc: 0.950 max roc: 0.950\n",
      ">> Training model Ganomaly. Epoch 3/10                                          \n",
      "result: OrderedDict([('Avg Run Time (ms/batch)', 6.909267902374268), ('roc', 0.9723012595557955)])\n",
      "   Avg Run Time (ms/batch): 6.909 roc: 0.972 max roc: 0.972\n",
      ">> Training model Ganomaly. Epoch 4/10                                          \n",
      "result: OrderedDict([('Avg Run Time (ms/batch)', 6.773579120635986), ('roc', 0.996380428352354)])\n",
      "   Avg Run Time (ms/batch): 6.774 roc: 0.996 max roc: 0.996\n",
      ">> Training model Ganomaly. Epoch 5/10                                          \n",
      "result: OrderedDict([('Avg Run Time (ms/batch)', 6.647365093231201), ('roc', 0.9993165201109651)])\n",
      "   Avg Run Time (ms/batch): 6.647 roc: 0.999 max roc: 0.999\n",
      ">> Training model Ganomaly. Epoch 6/10                                          \n",
      "result: OrderedDict([('Avg Run Time (ms/batch)', 6.460514068603516), ('roc', 0.9994615122965753)])\n",
      "   Avg Run Time (ms/batch): 6.461 roc: 0.999 max roc: 0.999\n",
      ">> Training model Ganomaly. Epoch 7/10                                          \n",
      "result: OrderedDict([('Avg Run Time (ms/batch)', 6.748340129852295), ('roc', 0.9996968693302599)])\n",
      "   Avg Run Time (ms/batch): 6.748 roc: 1.000 max roc: 1.000\n",
      " 32%|█████████████▌                            | 34/105 [00:01<00:02, 24.98it/s]   Reloading net d\n",
      ">> Training model Ganomaly. Epoch 8/10                                          \n",
      "result: OrderedDict([('Avg Run Time (ms/batch)', 6.769115924835205), ('roc', 0.999921505110783)])\n",
      "   Avg Run Time (ms/batch): 6.769 roc: 1.000 max roc: 1.000\n",
      ">> Training model Ganomaly. Epoch 9/10                                          \n",
      "result: OrderedDict([('Avg Run Time (ms/batch)', 6.691620349884033), ('roc', 0.999886788671975)])\n",
      "   Avg Run Time (ms/batch): 6.692 roc: 1.000 max roc: 1.000\n",
      ">> Training model Ganomaly. Epoch 10/10                                         \n",
      "result: OrderedDict([('Avg Run Time (ms/batch)', 6.725645065307617), ('roc', 0.9998205466435139)])\n",
      "   Avg Run Time (ms/batch): 6.726 roc: 1.000 max roc: 1.000\n",
      ">> Training model Ganomaly.[Done]\n"
     ]
    }
   ],
   "source": [
    "!python3 train.py \\\n",
    "    --dataset mnist \\\n",
    "    --niter 10 \\\n",
    "    --nc 1 \\\n",
    "    --batchsize 64 \\\n",
    "    --abnormal_class 0 \\\n",
    "    --display"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "[CIFAR10] 무조건 cat[3]은 정상(학습,테스트용), dog[5]는 비정상(테스트용) -- 성능 안 좋음"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Files already downloaded and verified\n",
      "Files already downloaded and verified\n",
      "Setting up a new session...\n",
      ">> Training model Ganomaly.\n",
      ">> Training model Ganomaly. Epoch 1/10                                          \n",
      "result: OrderedDict([('Avg Run Time (ms/batch)', 6.75581693649292), ('roc', 0.56236525)])\n",
      "   Avg Run Time (ms/batch): 6.756 roc: 0.562 max roc: 0.562\n",
      ">> Training model Ganomaly. Epoch 2/10                                          \n",
      "result: OrderedDict([('Avg Run Time (ms/batch)', 6.803743839263916), ('roc', 0.5415795833333333)])\n",
      "   Avg Run Time (ms/batch): 6.804 roc: 0.542 max roc: 0.562\n",
      ">> Training model Ganomaly. Epoch 3/10                                          \n",
      "result: OrderedDict([('Avg Run Time (ms/batch)', 6.685209274291992), ('roc', 0.5328973333333333)])\n",
      "   Avg Run Time (ms/batch): 6.685 roc: 0.533 max roc: 0.562\n",
      ">> Training model Ganomaly. Epoch 4/10                                          \n",
      "result: OrderedDict([('Avg Run Time (ms/batch)', 6.821908950805664), ('roc', 0.5560896666666666)])\n",
      "   Avg Run Time (ms/batch): 6.822 roc: 0.556 max roc: 0.562\n",
      ">> Training model Ganomaly. Epoch 5/10                                          \n",
      "result: OrderedDict([('Avg Run Time (ms/batch)', 6.782023906707764), ('roc', 0.54292675)])\n",
      "   Avg Run Time (ms/batch): 6.782 roc: 0.543 max roc: 0.562\n",
      ">> Training model Ganomaly. Epoch 6/10                                          \n",
      "result: OrderedDict([('Avg Run Time (ms/batch)', 6.837742328643799), ('roc', 0.5438496666666667)])\n",
      "   Avg Run Time (ms/batch): 6.838 roc: 0.544 max roc: 0.562\n",
      ">> Training model Ganomaly. Epoch 7/10                                          \n",
      "result: OrderedDict([('Avg Run Time (ms/batch)', 6.863069534301758), ('roc', 0.5689701666666667)])\n",
      "   Avg Run Time (ms/batch): 6.863 roc: 0.569 max roc: 0.569\n",
      ">> Training model Ganomaly. Epoch 8/10                                          \n",
      "result: OrderedDict([('Avg Run Time (ms/batch)', 6.7362213134765625), ('roc', 0.5689064166666666)])\n",
      "   Avg Run Time (ms/batch): 6.736 roc: 0.569 max roc: 0.569\n",
      ">> Training model Ganomaly. Epoch 9/10                                          \n",
      "result: OrderedDict([('Avg Run Time (ms/batch)', 6.548442840576172), ('roc', 0.5490979166666666)])\n",
      "   Avg Run Time (ms/batch): 6.548 roc: 0.549 max roc: 0.569\n",
      ">> Training model Ganomaly. Epoch 10/10                                         \n",
      "result: OrderedDict([('Avg Run Time (ms/batch)', 6.464540958404541), ('roc', 0.5553025)])\n",
      "   Avg Run Time (ms/batch): 6.465 roc: 0.555 max roc: 0.569\n",
      ">> Training model Ganomaly.[Done]\n"
     ]
    }
   ],
   "source": [
    "!python3 train.py \\\n",
    "    --dataset cifar10 \\\n",
    "    --niter 10 \\\n",
    "    --nc 3 \\\n",
    "    --batchsize 64 \\\n",
    "    --abnormal_class dog \\\n",
    "    --display"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Custom Dataset - UCSD Ped1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Setting up a new session...\n",
      "\n",
      "Loading pre-trained networks.\n",
      "\tDone.\n",
      "\n",
      ">> Training model Ganomaly.\n",
      ">> Training model Ganomaly. Epoch 201/201                                       \n",
      ">> Training model Ganomaly.[Done]\n"
     ]
    }
   ],
   "source": [
    "!python3 train.py \\\n",
    "    --dataset custom_ucsd \\\n",
    "    --isize 64 \\\n",
    "    --iter 200 \\\n",
    "    --niter 201 \\\n",
    "    --resume './output/ganomaly/custom_ucsd/train/weights' \\\n",
    "    --batchsize 64 \\\n",
    "    --save_image_freq 10 \\\n",
    "    --display"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Setting up a new session...\n",
      "   Loaded weights.\n",
      "산점도 저장 완료!\n",
      "result: OrderedDict([('Avg Run Time (ms/batch)', 3.453850746154785), ('roc', 0.824375)])\n"
     ]
    }
   ],
   "source": [
    "!python3 test.py \\\n",
    "    --dataset custom_ucsd \\\n",
    "    --isize 64 \\\n",
    "    --load_weights \\\n",
    "    --batchsize 64 \\\n",
    "    --display"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1"
  },
  "kernelspec": {
   "display_name": "Python 3.8.10 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
